services:
  haproxy:
    extends:
      file: ./docker-compose.base.yml
      service: haproxy

  django:
    extends:
      file: ./docker-compose.base.yml
      service: django

  opensearch:
    image: opensearchproject/opensearch:2.12.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  # cache:
  #   image: your-cache-image:latest   # replace with actual image
  #   container_name: cache
  #   ports:
  #     - "6379:6379"                  # if Redis-compatible
  #   volumes:
  #     - cache-data:/data

volumes:
  opensearch-data:
  cache-data:
