services:
  haproxy:
    image: haproxy:2.9
    container_name: haproxy
    ports:
      - "80:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - django

  django:
    build: .
    env_file: .env
    environment:
      SEARCH_ENABLED: "false"      
      SQLITE_PATH: /data/db.sqlite3  
    expose:
      - "8000"
    volumes:
      - db-data:/data
      - media-data:/app/media
      - .:/app                     
    command: >
      sh -c "
        python manage.py makemigrations --noinput || true &&
        python manage.py migrate --noinput &&
        python manage.py seed  &&
        python manage.py runserver 0.0.0.0:8000
      "

volumes:
  db-data:
  media-data:
