# Generated by Django 4.2.23 on 2025-08-26 23:22

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_yearlysales_book_total_sales_alter_review_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.author_image_upload_to),
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.book_cover_upload_to),
        ),
    ]
